-- =========================================================================
-- VESTIBULAR+ STATUS 16: Questoes Historia, Geografia, Portugues
-- 11 questoes por materia (3 facil, 2 medio, 3 dificil, 3 genio)
-- Execute no Supabase SQL Editor: jruyyzftoplcobketrsf
-- =========================================================================

-- HISTORIA (11 questoes)
DO $$
DECLARE mid uuid; aid uuid;
BEGIN
  SELECT id INTO mid FROM public.materias WHERE nome = 'Historia' LIMIT 1;
  SELECT id INTO aid FROM public.treineiro_aulas WHERE materia_id = mid LIMIT 1;
  IF mid IS NOT NULL AND aid IS NOT NULL THEN
    INSERT INTO public.questoes (materia_id,aula_id,enunciado,alternativas,resposta_correta,comentario,dificuldade,fonte,ano) VALUES
    (mid,aid,'O sistema de capitanias hereditarias de 1534 visava:','[{"letra":"A","texto":"Colonizar com recursos dos donatarios"},{"letra":"B","texto":"Abolir o trabalho indigena"},{"letra":"C","texto":"Industrializar precocemente"},{"letra":"D","texto":"Criar republicas autonomas"},{"letra":"E","texto":"Descobrir ouro no interior"}]','A','A Coroa delegou custos de exploracao aos donatarios por falta de recursos proprios.','facil','ENEM',2024),
    (mid,aid,'O ciclo do ouro em Minas Gerais no sec. XVIII impulsionou:','[{"letra":"A","texto":"Urbanizacao e transferencia da capital para o Rio"},{ "letra":"B","texto":"Fim do Pacto Colonial"},{ "letra":"C","texto":"Estagnacao das artes barrocas"},{ "letra":"D","texto":"Unificacao politica da America do Sul"},{ "letra":"E","texto":"Declinio das rotas de tropeiros"}]','A','A mineracao gerou urbanismo e integrou regioes, levando a capital ao Rio em 1763.','facil','Vestibulares',2024),
    (mid,aid,'A Lei de Terras de 1850 estabeleceu que o acesso a terra publica ocorreria por:','[{"letra":"A","texto":"Compra e venda em leilao"},{"letra":"B","texto":"Usucapiao"},{"letra":"C","texto":"Doacao de sesmarias"},{"letra":"D","texto":"Distribuicao a imigrantes"},{"letra":"E","texto":"Loteamento quilombola"}]','A','A lei restringia o acesso a terra para criar exercito de trabalhadores assalariados nas fazendas.','facil','ENEM',2023),
    (mid,aid,'A Revolta da Vacina (1904) expressou descontentamento frente a:','[{"letra":"A","texto":"Autoritarismo sanitario e demolições do Bota-Abaixo"},{"letra":"B","texto":"Vacina apenas contra febre amarela"},{"letra":"C","texto":"Oposicao monarquista a Republica"},{"letra":"D","texto":"Insatisfacao dos cafeicultores"},{"letra":"E","texto":"Greve geral anarquista"}]','A','A revolta combinou a obrigatoriedade da vacina com a exclusao social das reformas urbanas.','medio','FUVEST',2024),
    (mid,aid,'O Estado Novo de Vargas (1937-45) combinou autoritarismo com:','[{"letra":"A","texto":"Industrializacao de base e CLT"},{"letra":"B","texto":"Abertura irrestrita ao capital estrangeiro"},{"letra":"C","texto":"Alinhamento total ao Eixo nazi-fascista"},{"letra":"D","texto":"Descentralizacao federativa"},{"letra":"E","texto":"Reforma agraria ampla"}]','A','Vargas centralizou o poder e promoveu industrias de base com tutela corporativista dos sindicatos.','medio','UNICAMP',2024),
    (mid,aid,'O Tratado de Methuen (1703) entre Portugal e Inglaterra:','[{"letra":"A","texto":"Inviabilizou a industria lusa e drenou ouro colonial para a Gra-Bretanha"},{"letra":"B","texto":"Criou a Alianca dos Portos Abertos"},{"letra":"C","texto":"Aboliu precocemente o trafico negreiro"},{"letra":"D","texto":"Dividiu o Brasil entre Franca e Inglaterra"},{"letra":"E","texto":"Garantiu monopolio portugues nas especiarias"}]','A','O Tratado dos Panos e Vinhos aprofundou o deficit portugues e a evasao do ouro para Londres.','dificil','UNESP',2024),
    (mid,aid,'O AI-5 (1968) permitiu ao Executivo militar:','[{"letra":"A","texto":"Suspender habeas corpus, fechar Congresso e censurar a imprensa"},{"letra":"B","texto":"Convocar Constituinte popular"},{"letra":"C","texto":"Instituir voto direto para Presidente"},{"letra":"D","texto":"Anistiar presos politicos"},{"letra":"E","texto":"Criar pluripartidarismo irrestrito"}]','A','O AI-5 inaugurou os anos de chumbo com fechamento politico total e suspensao de garantias.','dificil','FUVEST',2023),
    (mid,aid,'A Confederacao do Equador (1824) foi resposta a:','[{"letra":"A","texto":"Outorga autoritaria da Constituicao de 1824 com Poder Moderador"},{"letra":"B","texto":"Proibicao do trafico negreiro pelos ingleses"},{"letra":"C","texto":"Maioridade prematura de D. Pedro II"},{"letra":"D","texto":"Tratados de 1810 com a Inglaterra"},{"letra":"E","texto":"Dissolucao da Guarda Nacional"}]','A','O movimento de Frei Caneca reivindicava republica federalista contra a centralizacao do Poder Moderador.','dificil','UNICAMP',2023),
    (mid,aid,'Segundo Florentino e Chalhoub, o trafico negreiro no Brasil funcionava como:','[{"letra":"A","texto":"Negocio endogeno gerido por comerciantes locais articulados a aliancas africanas"},{"letra":"B","texto":"Monopolio exclusivo de banqueiros britanicos"},{"letra":"C","texto":"Mecanismo sem agencia das chefaturas africanas"},{"letra":"D","texto":"Atividade subsidiada pelo erario regio"},{"letra":"E","texto":"Mercado regulado pela Inquisicao"}]','A','O trafico era dominado por mercadores do Rio e Salvador com forte autonomia em relacao a metropole.','genio','USP',2024),
    (mid,aid,'A derrama em Minas Gerais e sua relacao com a Inconfidencia Mineira decorreram de:','[{"letra":"A","texto":"Esgotamento das jazidas que inviabilizava a cota fixa de 100 arrobas"},{"letra":"B","texto":"Aumento da produtividade aurifera sobretaxada"},{"letra":"C","texto":"Conflito entre jesuitas e paulistas"},{"letra":"D","texto":"Imposto de capitacao e fechamento do Distrito Diamantino"},{"letra":"E","texto":"Recusa dos fazendeiros paulistas em pagar o dizimo"}]','A','A exaustao do ouro tornava a cobranca de 100 arrobas uma ameaca ruinosa as elites devedoras.','genio','UNICAMP',2024),
    (mid,aid,'A transicao da economia acucareira para a cafeeira mobilizou qual modelo de trabalho compulsorio?','[{"letra":"A","texto":"Trafico interprovincial do Nordeste decadente para o Sudeste em expansao"},{"letra":"B","texto":"Substituicao por mao de obra indigena"},{"letra":"C","texto":"Sistema de meacao de Vergueiro em larga escala"},{"letra":"D","texto":"Servos camponeses com cartas de aforamento"},{"letra":"E","texto":"Trabalhadores livres urbanos das capitais"}]','A','Com o fim do trafico atlantico em 1850, o trafico interno transferiu escravizados nordestinos para o cafe do Sudeste.','genio','FUVEST',2024);
  END IF;
END$$;

-- GEOGRAFIA (11 questoes)
DO $$
DECLARE mid uuid; aid uuid;
BEGIN
  SELECT id INTO mid FROM public.materias WHERE nome = 'Geografia' LIMIT 1;
  SELECT id INTO aid FROM public.treineiro_aulas WHERE materia_id = mid LIMIT 1;
  IF mid IS NOT NULL AND aid IS NOT NULL THEN
    INSERT INTO public.questoes (materia_id,aula_id,enunciado,alternativas,resposta_correta,comentario,dificuldade,fonte,ano) VALUES
    (mid,aid,'O processo de conurbacao urbana e definido pelo:','[{"letra":"A","texto":"Crescimento horizontal que une fisicamente cidades vizinhas"},{"letra":"B","texto":"Esvaziamento dos centros rumo ao campo"},{"letra":"C","texto":"Planejamento de cidades-satelite"},{"letra":"D","texto":"Aumento da natalidade nas periferias"},{"letra":"E","texto":"Fechamento de rodovias metropolitanas"}]','A','A conurbacao ocorre quando o crescimento contínuo integra duas ou mais cidades em unico tecido urbano.','facil','ENEM',2024),
    (mid,aid,'O fenomeno microclimático de temperatura mais elevada nas areas centrais e chamado de:','[{"letra":"A","texto":"Ilha de calor"},{"letra":"B","texto":"Inversao termica"},{"letra":"C","texto":"Chuva acida"},{"letra":"D","texto":"Efeito estufa natural"},{"letra":"E","texto":"Vento catabatico"}]','A','O asfalto, concreto e falta de vegetacao absorvem e retêm mais calor gerando ilhas de calor.','facil','Vestibulares',2024),
    (mid,aid,'O bioma brasileiro com savana de arvores retorcidas e solos acidos e profundos e o:','[{"letra":"A","texto":"Cerrado"},{"letra":"B","texto":"Caatinga"},{"letra":"C","texto":"Pampa"},{"letra":"D","texto":"Pantanal"},{"letra":"E","texto":"Mata Atlantica"}]','A','O Cerrado e o bioma savanibrasil central, adaptado ao fogo periodico com vegetacao escleromorfa.','facil','ENEM',2023),
    (mid,aid,'A gentrificacao em centros urbanos contemporaneos traduz-se por:','[{"letra":"A","texto":"Valorizacao imobiliaria que expulsa indiretamente populacoes de menor renda"},{"letra":"B","texto":"Descentralizacao industrial com favelizacao"},{"letra":"C","texto":"Democratizacao do solo com loteamentos populares"},{"letra":"D","texto":"Proibicao da verticalizacao"},{"letra":"E","texto":"Estatizacao de edificios historicos"}]','A','A gentrificacao atrai investimentos e classes de maior renda, deslocando moradores tradicionais.','medio','FUVEST',2024),
    (mid,aid,'O fenomeno do El Nino decorre do:','[{"letra":"A","texto":"Aquecimento anomalo do Pacifico Equatorial e enfraquecimento dos ventos alisios"},{"letra":"B","texto":"Resfriamento do Atlantico Sul com mais furacoes"},{"letra":"C","texto":"Aumento da ressurgencia no Peru e Chile"},{"letra":"D","texto":"Fortalecimento dos alisios de leste"},{"letra":"E","texto":"Aquecimento exclusivo do Mar Mediterraneo"}]','A','El Nino altera a circulacao atmosferica global, causando secas no Nordeste e chuvas no Sul do Brasil.','medio','UNICAMP',2024),
    (mid,aid,'A projecao de Mercator e conforme e preserva angulos, mas distorce fortemente:','[{"letra":"A","texto":"As areas nas altas latitudes, tornando Groenlandia maior do que a Africa"},{"letra":"B","texto":"A proporcionalidade das areas equatoriais"},{"letra":"C","texto":"Distancias a partir de um ponto central"},{"letra":"D","texto":"O formato das rotas polares"},{"letra":"E","texto":"Os fusos horarios"}]','A','Mercator foi feita para navegacao maritima, causando superdimensionamento nas regioes polares.','dificil','UNESP',2024),
    (mid,aid,'Os Rios Voadores na Amazonia descrevem o mecanismo no qual:','[{"letra":"A","texto":"A evapotranspiracao florestal transporta vapor pelos alisios ate os Andes, abastecendo o Centro-Sul"},{"letra":"B","texto":"A agua dos degelos andinos corre por canais aereos ate o Atlantico"},{"letra":"C","texto":"Massas polares causam frentes frias no Norte no verao"},{"letra":"D","texto":"Queimadas geram chuvas torrenciais no litoral"},{"letra":"E","texto":"A brisa maritima empurra frentes quentes para o semiarido"}]','A','A floresta amazonica injeta bilhoes de litros de vapor na atmosfera, alimentando chuvas no Sudeste.','dificil','FUVEST',2023),
    (mid,aid,'A expansao agricola no MATOPIBA baseia-se prioritariamente em:','[{"letra":"A","texto":"Soja e milho em chapadoes do Cerrado com alta precisao tecnologica"},{"letra":"B","texto":"Cacau e cafe sombreado em varzeas umidas"},{"letra":"C","texto":"Policultura familiar com apoio agroecologico"},{"letra":"D","texto":"Cana-de-acucar para exportacao artesanal"},{"letra":"E","texto":"Fruticultura irrigada para mercado local"}]','A','O MATOPIBA e um polo do agronegocio de graos em larga escala no Cerrado setentrional.','dificil','UNICAMP',2023),
    (mid,aid,'Milton Santos aponta que o espaco geografico contemporaneo:','[{"letra":"A","texto":"Organiza-se em redes desiguais polarizadas por fluxos de informacao, financas e tecnologia"},{"letra":"B","texto":"Torna-se homogeneo eliminando disparidades regionais"},{"letra":"C","texto":"Desvincula-se de infraestruturas fisicas"},{"letra":"D","texto":"Subordina-se exclusivamente ao Estado-nacao isolacionista"},{"letra":"E","texto":"Regride a relacoes pre-capitalistas de autossuficiencia"}]','A','A densidade informacional concentra o poder de comando nos nos centrais da rede global.','genio','FUVEST',2024),
    (mid,aid,'A circulacao termohalina global (AMOC) corre risco de colapso sob aquecimento global por:','[{"letra":"A","texto":"Aporte de agua doce do degelo da Groenlandia reduzindo salinidade e impedindo afundamento das aguas densas"},{"letra":"B","texto":"Maior evaporacao tropical elevando salinidade no Artico"},{"letra":"C","texto":"Interrupcao da corrente de jato polar"},{"letra":"D","texto":"Intensificacao da ressurgencia no Oceano Indico"},{"letra":"E","texto":"Formacao excessiva de gelo na Antartida ocidental"}]','A','A perda de salinidade diminui a densidade da agua artica, travando a correia transportadora global.','genio','USP',2024),
    (mid,aid,'A reprimarizacao da pauta exportadora brasileira no sec. XXI reflete:','[{"letra":"A","texto":"A doenca holandesa pelo boom de commodities e sobrevalorizacao cambial que desestimula a industria"},{"letra":"B","texto":"Baixa competitividade da agricultura extensiva"},{"letra":"C","texto":"Aumento de tarifas protecionistas sobre semicondutores"},{"letra":"D","texto":"Autossuficiencia em bens de capital de alto valor"},{"letra":"E","texto":"Esgotamento das reservas minerais do Quadrilatero Ferrifero"}]','A','A sobrevalorizacao cambial pelas commodities fragilizou o parque industrial nacional.','genio','UNICAMP',2024);
  END IF;
END$$;
-- PORTUGUES (11 questoes)
DO $$
DECLARE mid uuid; aid uuid;
BEGIN
  SELECT id INTO mid FROM public.materias WHERE nome = 'Portugues' OR nome = 'Português' LIMIT 1;
  SELECT id INTO aid FROM public.treineiro_aulas WHERE materia_id = mid LIMIT 1;
  IF mid IS NOT NULL AND aid IS NOT NULL THEN
    INSERT INTO public.questoes (materia_id,aula_id,enunciado,alternativas,resposta_correta,comentario,dificuldade,fonte,ano) VALUES
    (mid,aid,'Na frase "O atleta voou na pista de corrida", a figura de linguagem em "voou" e:','[{"letra":"A","texto":"Metafora"},{"letra":"B","texto":"Pleonasmo"},{"letra":"C","texto":"Eufemismo"},{"letra":"D","texto":"Ironia"},{"letra":"E","texto":"Antitese"}]','A','Metafora e a transferencia do sentido literal (voar) para o figurado (correr rapidamente).','facil','ENEM',2024),
    (mid,aid,'Assinale a frase com uso CORRETO da crase:','[{"letra":"A","texto":"Fomos a praia no final da tarde."},{"letra":"B","texto":"Ele comecou a estudar cedo."},{"letra":"C","texto":"Entreguei o documento a um senhor."},{"letra":"D","texto":"Estavamos dispostos a colaborar."},{"letra":"E","texto":"Viajamos a pe pela trilha."}]','A','Ocorreu fusao da preposicao "a" com o artigo feminino "a" de "praia". Antes de verbo nao ocorre crase.','facil','Vestibulares',2024),
    (mid,aid,'O pronome "cujo" estabelece relacao de:','[{"letra":"A","texto":"Posse entre dois substantivos"},{"letra":"B","texto":"Causa e consequencia"},{"letra":"C","texto":"Oposicao e contradicao"},{"letra":"D","texto":"Finalidade ou objetivo"},{"letra":"E","texto":"Comparacao quantitativa"}]','A','"Cujo" e pronome relativo que liga dois nomes exprimindo posse, concordando com a coisa possuida.','facil','ENEM',2023),
    (mid,aid,'Em "Embora estivesse cansado, terminou o relatorio", a oração subordinada exprime valor de:','[{"letra":"A","texto":"Concessao"},{"letra":"B","texto":"Causa"},{"letra":"C","texto":"Condicao"},{"letra":"D","texto":"Consequencia"},{"letra":"E","texto":"Proporcao"}]','A','A conjuncao "embora" introduz subord. adverbial concessiva, obstaculos que nao impedem a acao.','medio','FUVEST',2024),
    (mid,aid,'Memorias Postumas de Bras Cubas (Machado de Assis) rompe com o Romantismo por meio de:','[{"letra":"A","texto":"Narrador defunto, ironia cetica e desnudamento da hipocrisia das elites"},{"letra":"B","texto":"Idealizacao da mulher pura e heroi indigena"},{"letra":"C","texto":"Linguagem empolada e sentimentalismo"},{"letra":"D","texto":"Determinismo biologico e zoomorfizacao"},{"letra":"E","texto":"Engajamento politico panfletario"}]','A','Machado desconstroi convencoes romanticas com humor fino e analise psicologica acida.','medio','UNICAMP',2024),
    (mid,aid,'Na oracao "Necessita-se de novos metodos pedagogicos", o "se" e:','[{"letra":"A","texto":"Indice de indeterminacao do sujeito"},{"letra":"B","texto":"Particula apassivadora"},{"letra":"C","texto":"Pronome reflexivo direto"},{"letra":"D","texto":"Conjuncao integrante"},{"letra":"E","texto":"Particula de realce"}]','A','Com VTI acompanhado de preposicao, o "se" indetermina o sujeito; verbo permanece na 3ª pessoa singular.','dificil','UNESP',2024),
    (mid,aid,'A funcao da linguagem predominante em dicionarios e gramaticas e a:','[{"letra":"A","texto":"Metalinguistica"},{"letra":"B","texto":"Fatica"},{"letra":"C","texto":"Conativa (apelativa)"},{"letra":"D","texto":"Emotiva (expressiva)"},{"letra":"E","texto":"Poetica"}]','A','A funcao metalinguistica centra-se no proprio codigo para esclarecer seu significado.','dificil','FUVEST',2023),
    (mid,aid,'No poema "Vou-me embora pra Pasargada" de Manuel Bandeira, o lirismo modernista manifesta-se por:','[{"letra":"A","texto":"Fuga evasiva a reino mitico de liberdade com coloquialidade e versos livres"},{"letra":"B","texto":"Rigor formal parnasiano com rimas ricas"},{"letra":"C","texto":"Critica social revolucionaria"},{"letra":"D","texto":"Misticismo religioso barroco"},{"letra":"E","texto":"Nacionalismo ufanista"}]','A','Pasargada simboliza o refugio do eu lirico contra a dor, com a estetica liberta do 1º Modernismo.','dificil','UNICAMP',2023),
    (mid,aid,'Em Grande Sertao: Veredas, Guimaraes Rosa consolida sua linguagem por meio de:','[{"letra":"A","texto":"Neologismos, sintaxe arcaica popular e fusao entre regionalismo e reflexao metafisica"},{"letra":"B","texto":"Reproducao fonetica passiva do dialeto caipira"},{"letra":"C","texto":"Epopeias classicas camonianas"},{"letra":"D","texto":"Prosa jornalistica linear"},{"letra":"E","texto":"Parnasianismo tardio"}]','A','Rosa transforma o sertao em palco metafisico universal reinventando a lingua portuguesa.','genio','FUVEST',2024),
    (mid,aid,'O conceito de texto de fruicao de Barthes aplicado a Clarice Lispector decorre de:','[{"letra":"A","texto":"Desestabilizacao das certezas linguisticas pelo colapso da narrativa tradicional e epifania ontologica"},{"letra":"B","texto":"Conforto estetico com enredos previsíveis"},{"letra":"C","texto":"Didatismo pedagogico sobre condutas eticas"},{"letra":"D","texto":"Emprego de formas canonicas do verso alexandrino"},{"letra":"E","texto":"Neutralidade descritiva sem envolvimento emotivo"}]','A','Clarice rompe a linearidade burguesa para captar o instante-ja e o amago das sensacoes.','genio','USP',2024),
    (mid,aid,'Na teoria dos atos de fala, "Declaro aberta a sessao" caracteriza-se como ato:','[{"letra":"A","texto":"Declarativo, pois altera o estado do mundo institucional pelo proprio ato de enunciacao valida"},{"letra":"B","texto":"Assertivo constatativo sujeito a julgamento de verdade"},{"letra":"C","texto":"Expressivo que reflete estado psicologico privado"},{"letra":"D","texto":"Diretivo que ordena tarefa fisica"},{"letra":"E","texto":"Compromissivo que impoe promessa futura"}]','A','Performativos criam realidade juridica/social quando cumpridas as condicoes de felicidade.','genio','UNICAMP',2024);
  END IF;
END$$;